// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmocrccexkcgizwsdwyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtb2NyY2NleGtjZ2l6d3Nkd3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjM5NTksImV4cCI6MjA3MjczOTk1OX0.eq2l36wiUXu316XhMDBIlYB0zT4YX2ZpBmTT6IDKuzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});